# Generated by Django 4.1 on 2022-11-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('documents', models.CharField(max_length=90)),
                ('amount', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='servicerequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=90)),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.services')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=90)),
                ('reqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.servicerequests')),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificatetype', models.CharField(max_length=90)),
                ('certificate', models.CharField(max_length=90)),
                ('reqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramaapp.servicerequests')),
            ],
        ),
    ]
